In [1]:
import json

In [2]:
import pandas as pd

In [3]:
actor_genre = {}

with open("imdb_movies_2000to2022.prolific.json", "r") as IMDB_file:
    for line in IMDB_file:
        movie = json.loads(line)
        genres = movie['genres']
        actors = movie['actors']

        for actor_id, actor_name in actors:
            if actor_id not in actor_genre:
                actor_genre[actor_id] = {}

            for genre in genres:
                if genre not in actor_genre[actor_id]:
                    actor_genre[actor_id][genre] = 0
                actor_genre[actor_id][genre] += 1

In [4]:
index = actor_genre.keys()

rows = [actor_genre[k] for k in index]

df = pd.DataFrame(rows, index=index)
df = df.fillna(0)

df

,Comedy,Fantasy,Romance,Drama,Mystery,Thriller,Action,Biography,Crime,War,...,Horror,Documentary,Sport,News,Family,Music,,Western,Short,Reality-TV
nm0000212,7.0,1.0,6.0,6.0,1.0,2.0,1.0,1.0,2.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0413168,7.0,3.0,5.0,12.0,5.0,2.0,14.0,4.0,6.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0000630,8.0,2.0,6.0,14.0,2.0,3.0,4.0,5.0,1.0,1.0,...,3.0,7.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0005227,10.0,1.0,2.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0
nm0864851,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nm9504284,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm10592896,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm7216750,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm0936300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nm10375007,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
df_norm = df.divide(df.sum(axis=1), axis=0)
df_norm.head(10)

,Comedy,Fantasy,Romance,Drama,Mystery,Thriller,Action,Biography,Crime,War,...,Horror,Documentary,Sport,News,Family,Music,,Western,Short,Reality-TV
nm0000212,0.250000,0.035714,0.214286,0.214286,0.035714,0.071429,0.035714,0.035714,0.071429,0.035714,...,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
nm0413168,0.081395,0.034884,0.058140,0.139535,0.058140,0.023256,0.162791,0.046512,0.069767,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
nm0000630,0.112676,0.028169,0.084507,0.197183,0.028169,0.042254,0.056338,0.070423,0.014085,0.014085,...,0.042254,0.098592,0.042254,0.014085,0.00,0.0,0.0,0.0,0.0,0.0
nm0005227,0.400000,0.040000,0.080000,0.080000,0.000000,0.040000,0.040000,0.000000,0.000000,0.000000,...,0.040000,0.000000,0.040000,0.000000,0.08,0.0,0.0,0.0,0.0,0.0
nm0864851,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.333333,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
nm0828288,0.119403,0.000000,0.000000,0.059701,0.044776,0.149254,0.014925,0.000000,0.044776,0.000000,...,0.522388,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
nm0933983,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.333333,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
nm0329491,0.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.333333,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
nm0000417,0.119048,0.023810,0.000000,0.190476,0.071429,0.095238,0.119048,0.000000,0.095238,0.000000,...,0.119048,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0
nm0000603,0.062500,0.031250,0.062500,0.375000,0.062500,0.062500,0.000000,0.093750,0.062500,0.000000,...,0.031250,0.031250,0.000000,0.000000,0.00,0.0,0.0,0.0,0.0,0.0

In [10]:
from scipy.sparse import lil_matrix
import scipy.spatial.distance

In [14]:
target_actor_id = "nm1165110"

target_actor = df_norm.loc[target_actor_id]
distances = scipy.spatial.distance.cdist(df_norm,[target_actor],metric='cosine').flatten()

query_distances = list(zip(df.index,distances))

for similar_actor_id, similar_genre_score in sorted(query_distances,key=lambda x:x[1], reverse=False)[:10]:
    print(similar_actor_id, similar_genre_score)

nm1165110 0.0
nm0000129 0.02688463061355484
nm0147147 0.04459907371977079
nm0829032 0.0452033630127715
nm5899377 0.04878254078965638
nm1679372 0.051694237969527435
nm0003244 0.053414613481432505
nm0636280 0.05652570932413603
nm0607884 0.05652570932413603
nm2018237 0.05800371753039035

In [15]:
# change for eucledean

target_actor_id = "nm1165110"

target_actor = df_norm.loc[target_actor_id]
distances = scipy.spatial.distance.cdist(df_norm,[target_actor],metric='euclidean').flatten()

query_distances = list(zip(df.index,distances))

for similar_actor_id_similar_genre_score in sorted(query_distances,key=lambda x:x[1], reverse=False)[:10]:
    print(similar_actor_id, similar_genre_score)

nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035
nm2018237 0.05800371753039035